# Generated by Django 5.1.6 on 2025-03-05 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Variable name or key",
                        max_length=100,
                        verbose_name="Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Variable value (may be encrypted for secret type)",
                        verbose_name="Value",
                    ),
                ),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("secret", "Secret"),
                            ("json", "JSON"),
                            ("url", "URL"),
                        ],
                        default="text",
                        help_text="Type of this variable",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this variable",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variable is enabled",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "_is_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this value is currently encrypted",
                        verbose_name="Is Encrypted",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Environment this variable belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environment",
                "ordering": ["key"],
                "unique_together": {("project", "key")},
            },
        ),
    ]
