# Generated by Django 5.1.6 on 2025-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="file_content",
            field=models.BinaryField(
                blank=True, help_text="Binary content of uploaded file", null=True
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="file_name",
            field=models.CharField(
                blank=True,
                help_text="Original filename of uploaded file",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of uploaded file",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="variable_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("secret", "Secret"),
                    ("json", "JSON"),
                    ("url", "URL"),
                    ("file", "File"),
                ],
                default="text",
                help_text="Type of this variable",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
