# Generated by Django 5.1.6 on 2025-03-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_protocols", "0004_remove_testprotocol_verification_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("started", "Started"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("aborted", "Aborted"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
