# Generated by Django 5.1.6 on 2025-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_protocols", "0008_verificationmethod_execution_step_verificationresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionstep",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
