# Generated by Django 5.1.6 on 2025-03-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_protocols", "0009_executionstep_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationmethod",
            name="test_protocol",
        ),
    ]
