# Generated by Django 5.1.6 on 2025-03-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_protocols", "0012_alter_verificationresult_verification_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectionconfig",
            name="host",
        ),
        migrations.RemoveField(
            model_name="connectionconfig",
            name="password",
        ),
        migrations.RemoveField(
            model_name="connectionconfig",
            name="port",
        ),
        migrations.RemoveField(
            model_name="connectionconfig",
            name="secret_key",
        ),
        migrations.RemoveField(
            model_name="connectionconfig",
            name="username",
        ),
    ]
