# Generated by Django 5.1.6 on 2025-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_protocols", "0013_remove_connectionconfig_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionstep",
            name="args",
        ),
    ]
